spring.application.name=notification-service
server.port=8083

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=swastikthakur2604@gmail.com
spring.mail.password=fwiw sqan bhub swbg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true